image: maven:3-jdk-13

variables:
  MAVEN_CLI_OPTS: "--batch-mode clean"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - mvn $MAVEN_CLI_OPTS compile

stages:
  - build
  - test
  - report
  - pages

build:
  stage: build
  before_script: []
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

report:
  stage: report
  script:
    - mvn $MAVEN_CLI_OPTS site

pages:
  stage: pages
  dependencies:
    - report
  script:
    - mvn $MAVEN_CLI_OPTS site
    - mv ./target/site ./target/public
    - mv ./target/public .
  artifacts:
    paths:
      - public