image: maven:3-jdk-13

variables:
  MAVEN_CLI_OPTS: "--batch-mode clean"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - syntax
  - build
  - test
  - pages

syntax-check:
  stage: syntax
  script:
    - mvn $MAVEN_CLI_OPTS verify

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

pages:
  stage: pages
  script:
    - mvn $MAVEN_CLI_OPTS site
    - mv ./target/site ./target/public
    - mv ./target/public .
  artifacts:
    paths:
      - public
  only:
    - master
